FROM registry.cn-hangzhou.aliyuncs.com/jingansi/nginx:1.21.4

RUN bash -c "mkdir -p /usr/share/nginx/html/wanglou"

COPY ./dist /usr/share/nginx/html/wanglou

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/sbin

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]
